<?php

namespace AppBundle\Repository;

/**
 * QuestionPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionPoolRepository extends \Doctrine\ORM\EntityRepository
{
}
