<?php

namespace AppBundle\Repository;

/**
 * QuestionOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
