<?php

namespace AppBundle\Repository;

/**
 * SurveryResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveryResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
