<?php

namespace AppBundle\Repository;

/**
 * SurveyPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyPoolRepository extends \Doctrine\ORM\EntityRepository
{
}
